// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48m8BRLM4887lg-fplePmN1GJAK6fPYY',
    appId: '1:295927756268:web:2a78cf9f784837af2efcc9',
    messagingSenderId: '295927756268',
    projectId: 'feddit-200e5',
    authDomain: 'feddit-200e5.firebaseapp.com',
    storageBucket: 'feddit-200e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboh-AioqXKdzVnDk_JNpC9_jEsTPrmDM',
    appId: '1:295927756268:android:fd0d9c798c6905782efcc9',
    messagingSenderId: '295927756268',
    projectId: 'feddit-200e5',
    storageBucket: 'feddit-200e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6oOXv-cBV1lrWXaJ7ZwWv-ZxGkfHkEE',
    appId: '1:295927756268:ios:ddce089fbefcf5102efcc9',
    messagingSenderId: '295927756268',
    projectId: 'feddit-200e5',
    storageBucket: 'feddit-200e5.appspot.com',
    iosClientId: '295927756268-5uqm3ttksilq3lqsjuj948qpenundoaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.feddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6oOXv-cBV1lrWXaJ7ZwWv-ZxGkfHkEE',
    appId: '1:295927756268:ios:ddce089fbefcf5102efcc9',
    messagingSenderId: '295927756268',
    projectId: 'feddit-200e5',
    storageBucket: 'feddit-200e5.appspot.com',
    iosClientId: '295927756268-5uqm3ttksilq3lqsjuj948qpenundoaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.feddit',
  );
}
